### ISSUE TITLE
Add typo3/neos|flow to requirements

### ISSUE THREAD

**Issue by RafaelKa** [dfeyer/Neos.Media.Exporter#1]
Very nice package.

When the time comes(import implemented || this package is usable) please add typo3/neos|flow in composers requirements for listing this package on [neos.io packages](https://www.neos.io/download-and-extend/packages.html) page.

**Comment by dfeyer** [comment]
Don't need to add this dependency to be listed, this package depend on typo3/media package, and the media package depends on flow 

To be listed on neos.io it's just the package type that need to be correctly defined (like in this package neos-package)

**Comment by dfeyer** [comment]
And to be listed on neos.io this package need to be registred on packagist, but as it's just a prototype it's not a the moment.
